# Generated by Django 5.2.7 on 2025-11-05 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dias_contratados', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='dias_restantes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suscripciones', to='suscripciones.plan'),
        ),
    ]
