# Generated by Django 5.2.7 on 2026-01-13 00:47

import suscripciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0003_solicitudsuscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudsuscripcion',
            name='comprobante_pago',
            field=models.FileField(upload_to='comprobantes_suscripcion/', validators=[suscripciones.models.validate_comprobante_file]),
        ),
    ]
