# Generated by Django 5.2.7 on 2025-11-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('nombre_artistico', models.CharField(blank=True, max_length=100, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=15, null=True)),
                ('telegram_contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('edad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('T', 'Transgénero')], max_length=1, null=True)),
                ('peso', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('altura', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('medidas', models.CharField(blank=True, max_length=50, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
