# Generated by Django 5.2.7 on 2025-10-29 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilModelo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_modelo', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tarifa_por_hora', models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa por hora en la moneda local', max_digits=10, null=True)),
                ('servicios_ofrecidos', models.TextField(blank=True, help_text='Descripción de servicios ofrecidos')),
                ('disponibilidad', models.CharField(blank=True, help_text='Horarios de disponibilidad', max_length=200)),
                ('acepta_visitas_domicilio', models.BooleanField(default=False)),
                ('acepta_encuentros_hotel', models.BooleanField(default=False)),
                ('perfil_activo', models.BooleanField(default=True, help_text='Perfil visible en búsquedas')),
                ('perfil_destacado', models.BooleanField(default=False, help_text='Perfil destacado en la plataforma')),
                ('visualizaciones', models.PositiveIntegerField(default=0, help_text='Número de veces que el perfil ha sido visto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil de Modelo',
                'verbose_name_plural': 'Perfiles de Modelos',
            },
        ),
    ]
