# Generated by Django 5.2.7 on 2026-01-24 16:33

import perfiles.models
import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
                'ordering': ['ordering', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='GaleriaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=perfiles.models.ruta_galeria, validators=[usuarios.models.validate_image_file])),
                ('orden', models.PositiveIntegerField(default=0)),
                ('es_publica', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PerfilLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('nombre_artistico', models.CharField(max_length=100)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to=perfiles.models.ruta_foto_perfil, validators=[usuarios.models.validate_image_file])),
                ('foto_portada', models.ImageField(blank=True, null=True, upload_to=perfiles.models.ruta_foto_perfil, validators=[usuarios.models.validate_image_file])),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, help_text='Solo números, con código país', max_length=20, null=True)),
                ('telegram_contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('tarifa_desde', models.PositiveIntegerField(blank=True, help_text="Valor referencial 'desde'", null=True)),
                ('edad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('T', 'Transgénero')], default='F', max_length=1)),
                ('altura', models.PositiveSmallIntegerField(blank=True, help_text='En cm', null=True)),
                ('peso', models.PositiveSmallIntegerField(blank=True, help_text='En kg', null=True)),
                ('medidas', models.CharField(blank=True, help_text='Ej: 90-60-90', max_length=20, null=True)),
                ('color_pelo', models.CharField(blank=True, max_length=30, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('esta_publico', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudCambioCiudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('nota_admin', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Cambio de Ciudad',
                'verbose_name_plural': 'Solicitudes de Cambio de Ciudad',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('categoria', models.CharField(default='General', max_length=50)),
            ],
        ),
    ]
