# Generated by Django 5.2.7 on 2026-01-24 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfillike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfilmodelo',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfiles', to='perfiles.ciudad'),
        ),
        migrations.AddField(
            model_name='perfilmodelo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_modelo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfillike',
            name='perfil_modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='perfiles.perfilmodelo'),
        ),
        migrations.AddField(
            model_name='galeriafoto',
            name='perfil_modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria_fotos', to='perfiles.perfilmodelo'),
        ),
        migrations.AddField(
            model_name='perfilmodelo',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='perfiles', to='perfiles.servicio'),
        ),
        migrations.AddField(
            model_name='solicitudcambiociudad',
            name='ciudad_nueva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='perfiles.ciudad'),
        ),
        migrations.AddField(
            model_name='solicitudcambiociudad',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio_ciudad', to='perfiles.perfilmodelo'),
        ),
        migrations.AddField(
            model_name='perfilmodelo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='perfiles', to='perfiles.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='perfillike',
            unique_together={('user', 'perfil_modelo')},
        ),
    ]
