# Generated by Django 5.2.7 on 2025-11-04 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('perfil_modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='perfiles.perfilmodelo')),
            ],
        ),
    ]
