# Generated by Django 5.2.7 on 2025-10-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilmodelo',
            name='biografia',
            field=models.TextField(blank=True, help_text='Biografía o descripción personal'),
        ),
        migrations.AddField(
            model_name='perfilmodelo',
            name='ciudad',
            field=models.CharField(blank=True, editable=False, help_text='Ciudad (no editable directamente por la modelo)', max_length=100),
        ),
        migrations.AddField(
            model_name='perfilmodelo',
            name='estatura_cm',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Estatura en centímetros', null=True),
        ),
        migrations.AddField(
            model_name='perfilmodelo',
            name='foto_portada',
            field=models.ImageField(blank=True, help_text='Foto de portada del perfil', null=True, upload_to='perfiles/portadas/'),
        ),
        migrations.AddField(
            model_name='perfilmodelo',
            name='medidas',
            field=models.CharField(blank=True, help_text='Medidas corporales (ej: 90-60-90)', max_length=50),
        ),
        migrations.AddField(
            model_name='perfilmodelo',
            name='nombre_publico',
            field=models.CharField(blank=True, help_text='Nombre artístico o público', max_length=150),
        ),
        migrations.AddField(
            model_name='perfilmodelo',
            name='peso_kg',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Peso en kilogramos', null=True),
        ),
        migrations.AddField(
            model_name='perfilmodelo',
            name='telefono_trabajo',
            field=models.CharField(blank=True, help_text='Teléfono de contacto profesional', max_length=15),
        ),
        migrations.AddField(
            model_name='perfilmodelo',
            name='telegram_usuario',
            field=models.CharField(blank=True, help_text='Usuario de Telegram', max_length=100),
        ),
    ]
