# Generated by Django 5.2.7 on 2025-11-04 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria_fotos/')),
                ('perfil_modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria_fotos', to='perfiles.perfilmodelo')),
            ],
        ),
    ]
