# Generated by Django 5.2.7 on 2025-10-29 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_perfilmodelo_biografia_perfilmodelo_ciudad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del servicio', max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del servicio', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('perfil', models.ForeignKey(help_text='Perfil al que pertenece este servicio', on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='perfiles.perfilmodelo')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
    ]
