# Generated by Django 5.2.7 on 2026-01-24 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilmodelo',
            name='tarifa_desde',
        ),
    ]
