# Generated by Django 5.2.7 on 2025-10-29 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Foto de la galería', upload_to='perfiles/galeria/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('perfil', models.ForeignKey(help_text='Perfil al que pertenece esta foto', on_delete=django.db.models.deletion.CASCADE, related_name='galeria_fotos', to='perfiles.perfilmodelo')),
            ],
            options={
                'verbose_name': 'Foto de Galería',
                'verbose_name_plural': 'Fotos de Galería',
                'ordering': ['-created_at'],
            },
        ),
    ]
