# Generated by Django 5.2.7 on 2025-11-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilmodelo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='perfiles', to='perfiles.tag'),
        ),
    ]
