# Generated by Django 5.2.7 on 2025-10-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0005_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilmodelo',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags asociados al perfil', related_name='perfiles', to='perfiles.tag'),
        ),
    ]
