# Generated by Django 5.2.7 on 2025-11-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0006_perfilmodelo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilmodelo',
            name='ciudad',
            field=models.CharField(choices=[('Rancagua', 'Rancagua'), ('Curico', 'Curicó'), ('Talca', 'Talca'), ('Linares', 'Linares'), ('Chillan', 'Chillán'), ('Los Angeles', 'Los Ángeles'), ('Concepcion', 'Concepción'), ('Temuco', 'Temuco'), ('Pucon', 'Pucón'), ('Valdivia', 'Valdivia'), ('Osorno', 'Osorno'), ('Puerto Montt', 'Puerto Montt')], max_length=100),
        ),
    ]
