# Generated by Django 5.2.7 on 2025-11-05 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0007_alter_perfilmodelo_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCambioCiudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad_nueva', models.CharField(choices=[('Rancagua', 'Rancagua'), ('Curico', 'Curicó'), ('Talca', 'Talca'), ('Linares', 'Linares'), ('Chillan', 'Chillán'), ('Los Angeles', 'Los Ángeles'), ('Concepcion', 'Concepción'), ('Temuco', 'Temuco'), ('Pucon', 'Pucón'), ('Valdivia', 'Valdivia'), ('Osorno', 'Osorno'), ('Puerto Montt', 'Puerto Montt')], max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio_ciudad', to='perfiles.perfilmodelo')),
            ],
            options={
                'verbose_name': 'Solicitud de Cambio de Ciudad',
                'verbose_name_plural': 'Solicitudes de Cambio de Ciudad',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
