# Generated by Django 5.2.7 on 2025-11-10 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0008_solicitudcambiociudad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='precio',
        ),
    ]
