# Generated by Django 5.2.7 on 2026-01-13 00:47

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0009_remove_servicio_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeriafoto',
            name='imagen',
            field=models.ImageField(upload_to='galeria_fotos/', validators=[usuarios.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='perfilmodelo',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/', validators=[usuarios.models.validate_image_file]),
        ),
    ]
