# Generated by Django 5.2.7 on 2025-11-05 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resena',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='fecha_modificacion',
        ),
        migrations.AddField(
            model_name='resena',
            name='aprobada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resena',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
