# Generated by Django 5.2.7 on 2025-11-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_customuser_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento (debe ser mayor de 18 años)', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ha_solicitado_ser_modelo',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ha solicitado ser modelo'),
        ),
    ]
