# Generated by Django 5.2.7 on 2026-01-13 00:35

import django.db.models.deletion
import usuarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_customuser_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='foto_documento',
            field=models.ImageField(blank=True, null=True, upload_to='documentos/', validators=[usuarios.models.validate_documento]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='selfie_con_documento',
            field=models.ImageField(blank=True, null=True, upload_to='selfies/', validators=[usuarios.models.validate_selfie]),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Recuperación de Contraseña',
                'verbose_name_plural': 'Tokens de Recuperación de Contraseña',
                'ordering': ['-created_at'],
            },
        ),
    ]
